# Sidebar navigation

- label: 'PÃ¡gina Inicial'
  link: '/'
- label: 'Motivos para ter feito este site'
  link: '/motivos-do-site'
- label: 'Aprendendo'
  items:
    - label: 'Conceitos de Docker'
      link: '/learning/conceitos-docker'
    - label: 'Entendendo Backend'
      link: 'learning/backend-para-iniciantes'
    - label: 'ðŸš§ IntroduÃ§Ã£o Ã  computaÃ§Ã£o'
      link: '/learning/introducao-a-computacao'
    - label: 'ðŸš§ PrincÃ­pios SOLID'
      link: '/learning/solid'
- label: 'Resumos'
  items:
    - label: 'Devo fazer faculdade?'
      link: '/summary/devo-fazer-faculdade'
    - label: 'Primeira Expansion Week'
      link: '/summary/expansion-week-01'
    - label: '14 HÃ¡bitos de Desenvolvedores altamente produtivos'
      link: '/summary/zeno_book'
